### PR TITLE
Add support for new fields, introduce new Placeholder to reference existing values via one key

### PR DESCRIPTION
**Pull request by stmh**
This MR will add support for the `text_long` field and add support for the `allowed_formats` settiings totext and text_long fields.

This branch is based on `feature/refactor-template-handling`

### CODE REVIEW

**Comment by stmh** [comment]
doh, saw that there is a textaera -- but its different than my implementation -- i am confused...

**Comment by d34dman** [comment]
@stmh  i think we could decide to pick one of them. I think this one allows switching the text format on the fly without need of database changes. So looks like, this one is swappable with the one that supports CKEditor. While the other widget is swappable with a text field. Question is, do we need to support both?

**Comment by stmh** [comment]
i'd keep both of them but rename textarea to string_long to differentiate it better

**Comment by stmh** [comment]
ill apply this approach also to the text field, so text means "can be styled" and string means "store characters"

**Comment by stmh** [comment]
I am hijacking this MR as all the changes are interconnected. Here's what I did:

### fields
* Renamed `text` to `string` as it is usiing the `string` fieldtype under the hood so the code is consistent with D8
* renamed `textarea` to `string_long` field, as this field type does not support text formatters.
* introduce new `text`-field
* introduce new `text_long` field

### tests
* refactored tests to use all scaffolded files, not only the one declared in the test itself
* refactored array comparision to avoid false positive reports of data-mismatch

### Plaseholder-Service
* added a new placeholder `CREATE_OR_REUSE_ABSOLUTE_REFERENCE` to reference existing data from a different place, use `createAbsoluteReuseReference()` to create a placeholder. It suppots referencing a value deep in a multidimensional array by providing a list of keys describing the hierarchies.

**Pull request merged**
